### ISSUE TITLE
install.sh sets github username/email

### ISSUE THREAD

**Issue by daniel-packard** [rudolfb/ubuntu-xenial-elixir-install-shell-script#1]
I know, I know -- I shouldn't execute random scripts off the internet before reading them thoroughly... but you might put in a disclaimer that this script contains settings that are specific to you, the author, and that it doesn't _just install elixir_

https://github.com/rudolfb/ubuntu-xenial-elixir-install-shell-script/blob/master/install.sh#L46-L51

**Comment by rudolfb** [comment]
In the README I placed the following:

https://github.com/rudolfb/ubuntu-xenial-elixir-install-shell-script#installation

> Open the file with a text editor, search for GIT_USER_EMAIL and GIT_USER_NAME, enter the appropriate values and save the changes.

to advise to change these values.

**Comment by rudolfb** [comment]
The following replaces this script. Tested with Ubuntu 17.04 .

[https://github.com/rudolfb/ubuntu-elixir-elm-install-shell-script](https://github.com/rudolfb/ubuntu-elixir-elm-install-shell-script)
